name: Multipy runtime tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
        py-minor: [7]
        platform: [ubuntu-18.04]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout MultiPy
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup SSH (Click me for login details)
        uses: ./.github/actions/setup-ssh
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t multipy --progress=plain --build-arg PYTHON_VERSION=${{ matrix.python-version }} .

      - name: Test
        run: |
          docker run --rm multipy bash -c "if [[ ${{ matrix.py-minor }} -lt 8 ]]; then source ~/venvs/multipy/bin/activate; fi && multipy/runtime/build/test_deploy"

      - name: Compat Tests
        run: |
          docker run --rm multipy bash -c "if [[ ${{ matrix.py-minor }} -lt 8 ]]; then source ~/venvs/multipy/bin/activate; fi && pip install -r compat-requirements.txt && multipy/runtime/build/interactive_embedded_interpreter --pyscript multipy/runtime/test_compat.py"
